# Generated by Django 4.2.1 on 2023-07-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_highlight_delete_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='highlight',
        ),
        migrations.AddField(
            model_name='post',
            name='high',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.highlight'),
        ),
    ]
