# Generated by Django 4.2.1 on 2023-07-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_highlight_remove_post_highlight_post_high'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='high',
        ),
        migrations.AddField(
            model_name='highlight',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post'),
        ),
    ]
